---
driver:
  name: vagrant

provisioner:
  name: chef_zero

chef_versions:
  - 12

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
    - recipe[application_python_test]
  - name: django_init
    run_list:
    - recipe[application_python_test::django_init]
